=== gvp/gvp-word-addin/Tests/TestData/FontConversionTestData.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xi="http://www.w3.org/2001/XInclude">
  <xs:import namespace="http://www.w3.org/2001/XInclude" schemaLocation="https://www.w3.org/2001/XInclude.xsd" />
  <xs:element name="set" type="set" />
  <xs:complexType name="case">
    <xs:attribute name="local" type="xs:string" use="required" />
    <xs:attribute name="unicode" type="xs:string" use="required" />
    <xs:attribute name="comment" type="xs:string" use="optional" />
    <xs:attribute name="direction" type="direction" />
  </xs:complexType>
  <xs:complexType name="set">
    <xs:choice maxOccurs="unbounded">
      <xs:element name="case" type="case" />
      <xs:element name="set" type="set" />
      <xs:element ref="xi:include" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" />
  </xs:complexType>
  <xs:simpleType name="direction">
    <xs:restriction base="xs:string">
      <xs:enumeration value="to-unicode" />
      <xs:enumeration value="from-unicode" />
      <xs:enumeration value="both" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== gvp/gvp-word-addin/Tests/TestData/ThamesM.xml
<?xml version="1.0" encoding="UTF-8"?>
<set xsi:noNamespaceSchemaLocation="FontConversionTestData.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <case local="iрb-iука{ увfча" unicode="ш́рӣ-ш́уках̣ ува̄ча" />
  <case local="iрb iрb гуру-гаурfyга джаята{" unicode="ш́рӣ ш́рӣ гуру-гаура̄н̇га джаятах̣" />
  <case local="виджufйа" unicode="виджн̃а̄йа" />
  <case local="сарва-бхeта-хhдайаv" unicode="сарва-бхӯта-хр̣дайам̇" />
  <case local="g" unicode="р̣̄" />
  <case local="u" unicode="н̃" />
  <case local="z" unicode="у̃" />
</set>

=== gvp/gvp-word-addin/Tests/TestData/AARituPlus2.Common.xml
<?xml version="1.0" encoding="UTF-8"?>
<set xsi:noNamespaceSchemaLocation="FontConversionTestData.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <case local="&#xF5;" unicode="❀" comment="GVP logo light"/>
  <case local="&#xF8;" unicode="✿" comment="GVP logo dark" />
  <case local="nq;kZsèkuk|k%" unicode="दुर्योधनाद्याः" comment="Wrong order of र् and े" />
  <case local="dÙk±q" unicode="कर्त्तुं" comment="Wrong order of ु and ं" />
  <case local="'kÌknhuka" unicode="शङ्खादीनां" />
  <case local="rstks·a'klaHkoe~" unicode="तेजोंऽशसंभवम्" comment="BG page 107 ॥४१॥ Wrong order of anusvar and apostrophe http://gitabase.com/the/gita/eng/BG/10/41" />
  <case local="'qkp%" unicode="शुचः" comment="BG page 146 ॥५॥. Wrong order of u-sign and a-sign." />
  <case local="oiqnZèkr*~*" unicode="वपुर्दधत्”" comment="BG page 169 ॥५५॥. Wrong order of virama and apostrophe." />
  <case local="izofÙZkrqa" unicode="प्रवर्त्तितुं" comment="BG page 170 ॥५९॥. Wrong order of Z and something" />
  <case local="xhkr'kkL=L;kfi" unicode="गीतशास्त्रस्यापि" comment="BG page 172 ॥६४॥. Mistaken a-sign after i-sign." />
  <case local="iq#&quot;k'pkkfèknSore~" unicode="पुरुषश्चाधिदैवतम्" comment="BG page 80 ॥४॥ double a-sign" />
  <case local="dk;Zdkj.kdÙkZZ`ZRos" unicode="कार्यकारणकर्त्तृत्वे" comment="BG page 129 ॥२१॥ Double Z. Wrong order of `Z." />
  <case local="rn~~?kua" unicode="तद्‌घनं" comment="BG page 138 ॥२७॥ Double virama." />
  <case local="ozrkkfu" unicode="व्रतानि" comment="BG page 148 ॥१०॥. Triple a-sign." />
  <case local=";rLrr~~" unicode="यतस्तत्" comment="BG page 156 ॥२८॥ Double virama" />
  <case local="izzzzzzzzzzzzzzzzzzzÏreuqljke%" unicode="प्रकृतमनुसरामः" comment="BG page 161 ॥१८॥ Many zzzzz" />
  <case local="dk;ZsZ" unicode="कार्ये" comment="BG page 162 ॥२२॥. Extra Z." />
  <case local="fuxZZzUFkk" unicode="निर्ग्रन्था" comment="BG page 169 ॥५५॥. Extra Z" />
  <case local="Hkxoku~dk" unicode="भगवान्‌का" comment="Explicit halant, see http://unicode.org/faq/indic.html#2" />
  <case local="Hkxoku~ gh" unicode="भगवान् ही" comment="Explicit halant in the end of the word" />
  <case local="QykdkfÀ.kks" unicode="फलाकाङ्क्षिणो" comment="BG page 23 ॥४७॥" />
  <case local="lEeksgkr~~" unicode="सम्मोहात्" comment="BG page 26 ॥६३॥" />
  <case local="Js;ku~+" unicode="श्रेयाऩ्" comment="BG page 37 ॥३५॥" />
  <case local="prqFkkZss" unicode="चतुर्थो" comment="BG page 51 ॥४२॥" />
  <case local="fpÙk'kqf¼nk&lt;~îkZTKkunk&lt;~îeso" unicode="चित्तशुद्धिदार्ढ्याज्ज्ञानदाढ्यमेव" comment="BG page 52 ॥२॥" />
  <case local="cq¼îkRekdkj;Sso" unicode="बुद्ध्यात्माकारयैव" comment="BG page 62 ॥२०–२५॥" />
  <case local="ukjk;.kewfÙZkjso" unicode="नारायणमूर्त्तिरेव" comment="BG page 74 ॥१५॥" />
  <case local="deZZRo" unicode="कर्मत्व" comment="BG page 74 ॥१६॥" />
  <case local="en~;ksxkdkfÀ.k%" unicode="मद्‌योगाकाङ्क्षिणः" comment="BG page 82 ॥१४॥" />
  <case local="eRla;ksxkdkfÀ.kka" unicode="मत्संयोगाकाङ्क्षिणां" comment="BG page 101 ॥१०॥" />
  <case local="xHkZ±" unicode="गर्भं" comment="BG page 133 ॥३॥" />
  <case local="la{skis.k" unicode="संक्षेपेण" comment="BG page 143 ॥१६॥" />
  <case local="oÙZkrs" unicode="वर्त्तते" comment="BG page 155 ॥२६॥" />
  <case local="d&#xE096;" unicode="र्क" comment="PUA character" />
  <case local="d&#xE097;" unicode="र्कं" comment="PUA character" />
  <case local="&#xF076;&#xF06B;&#xF052;&#xF065;&#xF06B;&#xF064;&#xE094;&#xF020;&#xF06A;&#xF067;&#xF04C;&#xF03B;" unicode="आत्माके रहस्य" comment="Sentence in PUA" />
  <case local="d&#xE094;" unicode="के" comment="E094 is in PUA, but should map to े" />
</set>

=== gvp/gvp-word-addin/Tests/TestData/Rama Garamond Plus.xml
<?xml version="1.0" encoding="UTF-8"?>
<set xsi:noNamespaceSchemaLocation="FontConversionTestData.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <case local="çréçréguru-gauräìgau jayataù" unicode="śrīśrīguru-gaurāṅgau jayataḥ" />
  <case local="Ï" unicode="Ñ" />
  <case local="Î" unicode="Ã" />
  <case local="¾" unicode="[tilak]" />
  <case local="·" unicode="[lotus]" />
  <case local="Í" unicode="ī̃" />
  <case local="é" unicode="ī" />
</set>

=== gvp/gvp-word-addin/Tests/TestData/AA.Common.xml
<?xml version="1.0" encoding="UTF-8"?>
<set xsi:noNamespaceSchemaLocation="FontConversionTestData.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <set name="Symbols">
    <case local="ý" unicode="[" />
    <case local="»" unicode="÷" />
    <case local="^" unicode="‘" />
    <case local="&#x00B5;" unicode="&#x2014;" comment="Em dash"/>
    <case local="^^" unicode="“" comment="Two single quotation marks should be mapped to one double quotation mark" />
    <case local="**" unicode="”" comment="Two single quotation marks should be mapped to one double quotation mark" />
    <case local="AA" unicode="॥" comment="Two dandas should be converted into one double danda" />
  </set>
  <case local="," unicode="ए" />
  <case local="[" unicode="ख्" />
  <case local="mG" unicode="ऊ" />
  <case local="JhJhxq#&amp;xkSjkÂkS t;r%" unicode="श्रीश्रीगुरु–गौराङ्गौ जयतः" />
  <case local="bZn`'kks" unicode="ईदृशो" />
  <case local="izsenkukorh.kksZ" unicode="प्रेमदानावतीर्णो" />
  <case local="bR;FkZ%" unicode="इत्यर्थः" />
  <case local="ijenqyZHkRokr~" unicode="परमदुर्लभत्वात्" />
  <case local="uhZpSjfi" unicode="र्नीचैरपि" />
  <case local="loSZxksZihfo&quot;k;da" unicode="सर्वैर्गोपीविषयकं" />
  <case local="iq#&quot;kkFkks±dh" unicode="पुरुषार्थोंकी" />
  <case local="fu£o'ks&quot;kcqf¼" unicode="निर्विशेषबुद्धि" />
  <case local="tM+cfq¼ls" unicode="जड़बुद्धिसे" comment=" Wrong order of ◌ु and ◌ि" />
  <case local="D;kas" unicode="क्यों" comment=" Wrong order of ◌ो and ◌ं" />
  <case local="gaS" unicode="हैं" comment=" Wrong order of ◌ै and ◌ं" />
  <case local="Hksndks" unicode="भेदको" />
  <case local="ughsa" unicode="नहीं" comment=" Extra ◌े" />
  <case local="vkSj" unicode="और" />
  <case local="Ük`Âkjjfr" unicode="शृङ्गाररति" />
  <case local="¥glk" unicode="हिंसा" />
  <case local="nksuksa" unicode="दोनों" />
  <case local="lkefxz;ksasds" unicode="सामग्रियोंके" comment=" Extra ◌े" />
  <case local="tM+cqf¼okyss" unicode="जड़बुद्धिवाले" comment=" Extra ◌े" />
  <case local="oS&quot;.koèkeZesaa" unicode="वैष्णवधर्ममें" comment=" Extra ◌ं" />
  <case local="voLFkkessa" unicode="अवस्थामें" comment=" Extra ◌े" />
  <case local="O;fä;ksaesaaa" unicode="व्यक्तियोंमें" comment=" Three ◌ं" />
  <case local="d±ZZZ" unicode="र्कं" comment="Duplicates should be removed before swallowing." />
  <case local="gssSS" unicode="है" comment="◌ै swallows ◌े. With duplicates." />
  <case local="isz" unicode="प्रे" comment="Wrong order of ◌े and ◌र"/>
</set>
