=== gvp/gvp-word-addin/WordAddIn/Maps/Mapping.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xi="http://www.w3.org/2001/XInclude">
  <xs:import namespace="http://www.w3.org/2001/XInclude" schemaLocation="https://www.w3.org/2001/XInclude.xsd"/>
  <xs:element name="mapping" type="mapping"/>
  <xs:complexType name="entry">
    <xs:attribute name="from" type="xs:string" use="required" />
    <xs:attribute name="to" type="xs:string" use="required" />
    <xs:attribute name="order" type="xs:int" use="optional" />
    <xs:attribute name="comment" type="xs:string" use="optional" />
    <xs:attribute name="type" type="xs:string" use="optional" />
  </xs:complexType>
  <xs:complexType name="mapping">
    <xs:choice maxOccurs="unbounded">
      <xs:element name="entry" type="entry" />
      <xs:element name="mapping" type="mapping" />
      <xs:element ref="xi:include" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" />
  </xs:complexType>
</xs:schema>

=== gvp/gvp-word-addin/WordAddIn/Maps/Devanagari/AARituPlus2-Numbers.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xsi:noNamespaceSchemaLocation="..\Mapping.xsd"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:xi="http://www.w3.org/2001/XInclude">

  <!-- Overriding numbers -->
  <mapping name="Devanagari Numbers">
    <entry from="0" to="०" order="20" comment="0" />
    <entry from="1" to="१" order="20" comment="1" />
    <entry from="2" to="२" order="20" comment="2" />
    <entry from="3" to="३" order="20" comment="3" />
    <entry from="4" to="४" order="20" comment="4" />
    <entry from="5" to="५" order="20" comment="5" />
    <entry from="6" to="६" order="20" comment="6" />
    <entry from="7" to="७" order="20" comment="7" />
    <entry from="8" to="८" order="20" comment="8" />
    <entry from="9" to="९" order="20" comment="9" />
  </mapping>
  <mapping name="Arabic Numbers">
    <entry from="Œ" to="0" order="20" comment="0" />
    <entry from="ƒ" to="1" order="20" comment="1" />
    <entry from="„" to="2" order="20" comment="2" />
    <entry from="…" to="3" order="20" comment="3" />
    <entry from="†" to="4" order="20" comment="4" />
    <entry from="‡" to="5" order="20" comment="5" />
    <entry from="ˆ" to="6" order="20" comment="6" />
    <entry from="‰" to="7" order="20" comment="7" />
    <entry from="Š" to="8" order="20" comment="8" />
    <entry from="‹" to="9" order="20" comment="9" />
  </mapping>

  <xi:include href="AARituPlus2.xml"/>
</mapping>

=== gvp/gvp-word-addin/WordAddIn/Maps/Roman/DVRoman-TTSurekh.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xsi:noNamespaceSchemaLocation="..\Mapping.xsd"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <entry from='&#x00A1;' to='ā' />
  <entry from='&#x00A2;' to='ī' order='-1' />
  <entry from='&#x00A3;' to='ū' />
  <entry from='&#x00A4;' to='ṛ' />
  <entry from='&#x00A5;' to='ṝ' />
  <entry from='&#x00A7;' to='ṙ' />
  <entry from='&#x00AB;' to='ḻ' />
  <entry from='&#x00AC;' to='ḻ̄' />
  <entry from='&#x00AE;' to='ē' />
  <entry from='&#x00B0;' to='ō' />
  <entry from='&#x00B4;' to='ṅ' />
  <entry from='&#x00B5;' to='ñ' />
  <entry from='&#x00B6;' to='ṭ' />
  <entry from='&#x00B7;' to='ḍ' />
  <entry from='&#x00B8;' to='ṇ' />
  <entry from='&#x00BA;' to='ṉ' />
  <entry from='&#x00BB;' to='ẏ' />
  <entry from='&#x00BC;' to='ṟ' />
  <entry from='&#x00BD;' to='ḷ' />
  <entry from='&#x00BE;' to='ẕ' />
  <entry from='&#x00BF;' to='ś' />
  <entry from='&#x00C0;' to='ṣ' />
  <entry from='&#x00C4;' to='m̐' />
  <entry from='&#x00C5;' to='ḥ' />
  <entry from='&#x00C6;' to='ṃ' />
  <entry from='&#x00C7;' to='ḹ' />
  <entry from='&#x00C8;' to='ḏ' />
  <entry from='&#x00C9;' to='ṯ' />
  <entry from='&#x00CB;' to='Ā' />
  <entry from='&#x00CC;' to='Ī' />
  <entry from='&#x00CD;' to='Ū' />
  <entry from='&#x00CE;' to='Ṛ' />
  <entry from='&#x00CF;' to='Ṝ' />
  <entry from='&#x00D0;' to='Ṙ' />
  <entry from='&#x00D1;' to='Ḻ' order='-1' />
  <entry from='&#x00D2;' to='Ḻ̄' />
  <entry from='&#x00D3;' to='Ē' />
  <entry from='&#x00D5;' to='Ō' />
  <entry from='&#x00D7;' to='Ṅ' />
  <entry from='&#x00D8;' to='Ñ' />
  <entry from='&#x00D9;' to='Ṭ' />
  <entry from='&#x00DA;' to='Ḍ' />
  <entry from='&#x00DB;' to='Ṇ' />
  <entry from='&#x00DC;' to='Ṉ' />
  <entry from='&#x00DD;' to='Ẏ' />
  <entry from='&#x00DE;' to='Ṟ' />
  <entry from='&#x00DF;' to='Ḷ' />
  <entry from='&#x00E0;' to='Ẕ' />
  <entry from='&#x00E1;' to='Ś' />
  <entry from='&#x00E2;' to='Ṣ' />
  <entry from='&#x00E8;' to='M̐' />
  <entry from='&#x00E9;' to='Ḥ' />
  <entry from='&#x00EA;' to='Ṃ' />
  <entry from='&#x00EB;' to='Ḹ' />
  <entry from='&#x00EC;' to='Ḏ' />
  <entry from='&#x00ED;' to='Ṯ' />
  <entry from='&#x00EE;' to='ī' />
  <entry from='&#x00EF;' to='Ị' />
  <entry from='&#x00F0;' to='Ị̄' />
</mapping>

=== gvp/gvp-word-addin/WordAddIn/Maps/Devanagari/AA.Common.Post.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xsi:noNamespaceSchemaLocation="..\Mapping.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xi="http://www.w3.org/2001/XInclude">
  <mapping name="Devanagari Fixing">
    <entry from="ं([ऺऻा-ौ])" to="$1ं" type="regex" order="100" comment="Reorder anusvar and matra" />
    <entry from="ीे" to="ी" order="110" comment="Extra" />
    <entry from="।।" to="॥" order="110" comment="Combine double danda" />
    <entry from="्ा" to="" order="110" comment="Collapse ् and sign" />
    <entry from="्ऻ" to="ऺ" order="110" comment="Collapse ् and sign" />
    <entry from="्ॉ" to="ॅ" order="110" comment="Collapse ् and sign" />
    <entry from="्ॊ" to="ॆ" order="110" comment="Collapse ् and sign" />
    <entry from="्ो" to="े" order="110" comment="Collapse ् and sign" />
    <entry from="्ौ" to="ै" order="110" comment="Collapse ् and sign" />
    <entry from="(\p{Mn})\1+" to="$1" type="regex" order="110" comment="Remove duplicate non-spacing marks" />
    <entry from="अा" to="आ" order="110" comment="Combine" />
    <entry from="अऻ" to="ॴ" order="200" comment="VOWEL SIGN OOE" />
    <entry from="अॏ" to="ॵ" order="200" comment="VOWEL SIGN AW" />
    <entry from="अॉ" to="ऑ" order="200" comment="Combine" />
    <entry from="अॊ" to="ऒ" order="200" comment="Combine" />
    <entry from="अो" to="ओ" order="200" comment="Combine" />
    <entry from="अौ" to="औ" order="200" comment="Combine" />
    <entry from="आॅ" to="ऑ" order="200" comment="Combine" />
    <entry from="आे" to="ओ" order="200" comment="Combine" />
    <entry from="आै" to="औ" order="200" comment="Combine" />
    <entry from="आॆ" to="ऒ" order="200" comment="Combine" />
    <entry from="आऺ" to="ॴ" order="200" comment="VOWEL SIGN OE" />
    <entry from="एॅ" to="ऍ" order="200" comment="Combine" />
    <entry from="एॆ" to="ऎ" order="200" comment="Combine" />
    <entry from="एे" to="ऐ" order="200" comment="Combine" />
    <entry from="ाॅ" to="ॉ" order="200" comment="Combine" />
    <entry from="ाे" to="ो" order="200" comment="Combine" />
    <entry from="ाै" to="ौ" order="200" comment="Combine" />
    <entry from="ाॆ" to="ॊ" order="200" comment="Combine" />
    <entry from="&#x93E;&#x93A;" to="&#x93B;" order="200" comment="VOWEL SIGN OE" />
    <entry from="\u200C\b" to="" type="regex" order="220" comment="Remove ZWNJ in the end of the word" />
  </mapping>
  <mapping name="Jumping repha and short i sign">
    <!--
      All the consonants are converted to Unicode by the earlier mappings, but the jumping combining symbols not.
      Thus, Unicode UTF-16 codes are used for consonants and local 8bit codes for combining symbols.
      “From” uses regex character escape syntax https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-escapes-in-regular-expressions#character-escapes-in-net.
      “To” uses XML entity syntax.
    -->
    <entry from='\x66([\u0915-\u0939](\u094D[\u0915-\u0939])*)' to='$1&#x093F;' type="regex" comment="consonant+i" />
    <entry from='\xA3([\u0915-\u0939](\u094D[\u0915-\u0939])*)' to='र्$1&#x093F;' type="regex" comment="r+consonant+i" />
    <entry from='\xA5([\u0915-\u0939](\u094D[\u0915-\u0939])*)' to='$1&#x093F;&#x0902;' type="regex" comment="consonant+im" />
    <entry from='\xB2([\u0915-\u0939](\u094D[\u0915-\u0939])*)' to='र्$1&#x093F;&#x0902;' type="regex" comment="r+consonant+im" />
    <entry from='([\u0915-\u0939](\u094D[\u0915-\u0939])*[\u093A\u093B\u093E-\u094C]?)\x5A' to='र्$1' type="regex" comment="r+consonant" />
    <entry from="([\u0915-\u0939](\u094D[\u0915-\u0939])*[\u093A\u093B\u093E-\u094C]?)\x96" to="र्$1" type="regex" comment="r+consonant" />
    <entry from="([\u0915-\u0939](\u094D[\u0915-\u0939])*[\u093A\u093B\u093E-\u094C]?)\x97" to="र्$1&#x0902;" type="regex" comment="r+consonant+m" />
    <entry from="([\u0915-\u0939](\u094D[\u0915-\u0939])*[\u093A\u093B\u093E-\u094C]?)\xB1" to="र्$1&#x0902;" type="regex" comment="r+consonant+m" />
  </mapping>
</mapping>

=== gvp/gvp-word-addin/WordAddIn/Maps/Devanagari/AA.Common.Symbols.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xsi:noNamespaceSchemaLocation="..\Mapping.xsd"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <entry from="&amp;" to="–" />
  <entry from="&#xB5;" to="—" />
  <entry from="&#x03BC;" to="—" />
  <entry from="]" to="," />
  <entry from="_" to=";" />
  <entry from="\" to="?" />
  <entry from="-" to="." />
  <entry from="A" to="।" comment="danda" />
  <entry from="&#xFB;" to="॥" comment="double danda" />
  <entry from="^" to="‘" />
  <entry from="*" to="’" />
  <entry from="&#xDF;" to="“" />
  <entry from="&#xDE;" to="”" />
  <entry from="&#xFD;" to="[" />
  <entry from="@" to="/" />
  <entry from="&#x17E;" to="&lt;" />
  <entry from="&#xF1;" to="॰" />
  <entry from="$" to="+" />
  <entry from="&#xBB;" to="÷" />
  <entry from="&#xBE;" to="=" />
  <entry from="&#x178;" to="&gt;" />
  <entry from="&#xFE;" to="]" order="2" />
</mapping>

=== gvp/gvp-word-addin/WordAddIn/Maps/Devanagari/AARituPlus2.Common.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xsi:noNamespaceSchemaLocation="..\Mapping.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xi="http://www.w3.org/2001/XInclude">

  <xi:include href="AA.Common.Pre.xml"/>
  <xi:include href="AA.Common.xml"/>

  <mapping name="Specific AARituPlus2 Normal characters">
    <entry from="&#xF0;" to="प्त" />
    <entry from="&#xC8;" to="ऌ" comment="гласная л" />
    <entry from="&#x81;" to="क्च" />
    <entry from="&#xC9;" to="ङ्क्त" comment="н̇кта" />
    <entry from="&#xC0;" to="ङ्क्ष" comment="н̇кш̣а" />
    <entry from="&#xCC;" to="ङ्ख" comment="н̇кха" />
    <entry from="&#xD0;" to="ङ्घ" comment="н̇гха" />
    <entry from="&#x80;" to="ञ्च" />
    <entry from="&#x91;" to="ञ्ज" comment="н̃джа" />
    <entry from="&#xCB;" to="ल्ल" comment="лла" />
    <entry from="&#xFF;" to="ळ" comment="лла" />
    <entry from="&#x8D;" to="श्च" />
    <entry from="&#x82;" to="श्व" comment="ш̣ва" />
    <entry from="&#xD4;" to="ष्ट" comment="ш̣тта" />
    <entry from="&#xD7;" to="ष्ठ" comment="ш̣ттха" />
    <entry from="&#x92;" to="ु" />
    <entry from="&#x93;" to="ू" />
    <entry from="&#xA4;" to="ॄ" comment="р̣р̣" />
    <entry from="&#xC6;" to="ॢ" comment="??? гласная лл" />
    <entry from="&#x94;" to="े" />
    <entry from="&#x95;" to="ै" />
    <entry from="&#x99;" to="ैं" />
    <entry from="&#xC4;" to="्न" />
  </mapping>

  <xi:include href="AA.Common.Post.xml"/>

  <mapping name="Symbols">
    <entry from="&#xB9;" to="✕" />
    <entry from="&#x8E;" to="←" />
    <entry from="&#x8F;" to="→" />
  </mapping>
  <mapping name="Unknown">
    <!-- <entry from="&#xF6;" to="[e with chandrabindu]" comment="вирама с чандрабинду" />!!! -->
    <entry from="&#xF5;" to="[GVP logo white]" />
    <entry from="&#xF8;" to="[GVP logo black]" />
  </mapping>
</mapping>

=== gvp/gvp-word-addin/WordAddIn/Maps/Roman/Rama Garamond Plus.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xsi:noNamespaceSchemaLocation="..\Mapping.xsd"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <entry from='&#x00B5;' to='⚬' />
  <entry from='&#x00B7;' to='[lotus]' order='1000' />
  <entry from='&#x00BE;' to='[tilak]' order='1000' />
  <entry from='&#x00C0;' to='Ṁ' />
  <entry from='&#x00C1;' to='ē̃' order='3' />
  <entry from='&#x00C2;' to='ō̃' order='3' />
  <entry from='&#x00C3;' to='ā̃' order='-1' />
  <entry from='&#x00C4;' to='Ā' />
  <entry from='&#x00C5;' to='Ṛ' />
  <entry from='&#x00C7;' to='Ś' />
  <entry from='&#x00C8;' to='Ṝ' order='3' />
  <entry from='&#x00C9;' to='Ī' />
  <entry from='&#x00CB;' to='Ṇ' />
  <entry from='&#x00CC;' to='Ṅ' />
  <entry from='&#x00CD;' to='ī̃' order='3' />
  <entry from='&#x00CE;' to='Ã' />
  <entry from='&#x00CF;' to='Ñ' />
  <entry from='&#x00D1;' to='Ṣ' order='-1' />
  <entry from='&#x00D2;' to='Ḍ' />
  <entry from='&#x00D3;' to='ū̃' order='3' />
  <entry from='&#x00D6;' to='Ṭ' />
  <entry from='&#x00D7;' to='ẽ' />
  <entry from='&#x00D8;' to='ī̃' order='-1' />
  <entry from='&#x00D9;' to='Ḥ' />
  <entry from='&#x00DB;' to='´' />
  <entry from='&#x00DC;' to='Ū' />
  <entry from='&#x00DE;' to='Ḷ' />
  <entry from='&#x00E0;' to='ṁ' />
  <entry from='&#x00E1;' to='ē' />
  <entry from='&#x00E2;' to='ō' />
  <entry from='&#x00E4;' to='ā' />
  <entry from='&#x00E5;' to='ṛ' />
  <entry from='&#x00E7;' to='ś' />
  <entry from='&#x00E8;' to='ṝ' order='3' />
  <entry from='&#x00E9;' to='ī' />
  <entry from='&#x00EA;' to='ṙ' />
  <entry from='&#x00EB;' to='ṇ' />
  <entry from='&#x00EC;' to='ṅ' />
  <entry from='&#x00ED;' to='ĩ' />
  <entry from='&#x00EE;' to='ɔ' />
  <entry from='&#x00EF;' to='ñ' />
  <entry from='&#x00F1;' to='ṣ' order='-1' />
  <entry from='&#x00F2;' to='ḍ' />
  <entry from='&#x00F3;' to='ũ' />
  <entry from='&#x00F6;' to='ṭ' />
  <entry from='&#x00F7;' to='→' />
  <entry from='&#x00F8;' to='ī' order='-1' />
  <entry from='&#x00F9;' to='ḥ' />
  <entry from='&#x00FB;' to='&#x0301;' />
  <entry from='&#x00FC;' to='ū' />
  <entry from='&#x00FE;' to='l̐' />
  <entry from='&#x00FF;' to='ḷ' />
  <entry from='&#x0152;' to='◡' />
  <entry from='&#x03BC;' to='⚬' />
  <entry from='&#x2219;' to='[lotus]' order='999' />
  <entry from='&#xF101;' to='^' />
  <entry from='&#xF102;' to=' &#x0303;' />
  <entry from='&#xF103;' to='&#x0131;' />
  <entry from='&#xF104;' to='˙' />
</mapping>
