=== gvp/gvp-word-addin/WordAddIn/Maps/Mapping.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xi="http://www.w3.org/2001/XInclude">
  <xs:import namespace="http://www.w3.org/2001/XInclude" schemaLocation="https://www.w3.org/2001/XInclude.xsd"/>
  <xs:element name="mapping" type="mapping"/>
  <xs:complexType name="entry">
    <xs:attribute name="from" type="xs:string" use="required" />
    <xs:attribute name="to" type="xs:string" use="required" />
    <xs:attribute name="order" type="xs:int" use="optional" />
    <xs:attribute name="comment" type="xs:string" use="optional" />
    <xs:attribute name="type" type="xs:string" use="optional" />
  </xs:complexType>
  <xs:complexType name="mapping">
    <xs:choice maxOccurs="unbounded">
      <xs:element name="entry" type="entry" />
      <xs:element name="mapping" type="mapping" />
      <xs:element ref="xi:include" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" />
  </xs:complexType>
</xs:schema>

=== gvp/gvp-word-addin/WordAddIn/Maps/Devanagari/AA.Common.Numbers.xml
<?xml version="1.0" encoding="UTF-8"?>

<mapping xsi:noNamespaceSchemaLocation="..\Mapping.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <entry from="&#x8C;" to="०" />
  <entry from="&#x83;" to="१" />
  <entry from="&#x84;" to="२" />
  <entry from="&#x85;" to="३" />
  <entry from="&#x86;" to="४" />
  <entry from="&#x87;" to="५" />
  <entry from="&#x88;" to="६" />
  <entry from="&#x89;" to="७" />
  <entry from="&#x8A;" to="८" />
  <entry from="&#x8B;" to="९" />
</mapping>

=== gvp/gvp-word-addin/WordAddIn/Maps/Cyrillic/ThamesM.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xsi:noNamespaceSchemaLocation="..\Mapping.xsd"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <entry from='&#x0041;' to='а̄̃' order='3' />
  <entry from='&#x0042;' to='Ӣ' />
  <entry from='&#x0043;' to='о̄̃' order='3' />
  <entry from='&#x0044;' to='э̃' />
  <entry from='&#x0045;' to='Ӯ' />
  <entry from='&#x0046;' to='А̄' />
  <entry from='&#x0047;' to='Р̣̄' order='3' />
  <entry from='&#x0048;' to='Р̣' />
  <entry from='&#x0049;' to='Ш́' />
  <entry from='&#x004A;' to='о̄' />
  <entry from='&#x004B;' to='Л̣' />
  <entry from='&#x004C;' to='Д̣' />
  <entry from='&#x004E;' to='Т̣' />
  <entry from='&#x004F;' to='Ш̣' />
  <entry from='&#x0051;' to='ӣ̃' order='3' />
  <entry from='&#x0052;' to='р̣̄' order='-1' />
  <entry from='&#x0053;' to='н̃' order='-1' />
  <entry from='&#x0054;' to='Н̣' />
  <entry from='&#x0055;' to='Н̃' />
  <entry from='&#x0056;' to='М̇' />
  <entry from='&#x0057;' to='у̃' order='-1' />
  <entry from='&#x0058;' to='Х̣' />
  <entry from='&#x0059;' to='Н̇' />
  <entry from='&#x005A;' to='ӯ̃' order='3' />
  <entry from='&#x0061;' to='а̃' />
  <entry from='&#x0062;' to='ӣ' />
  <entry from='&#x0063;' to='е̃' />
  <entry from='&#x0064;' to='е̄' />
  <entry from='&#x0065;' to='ӯ' />
  <entry from='&#x0066;' to='а̄' />
  <entry from='&#x0067;' to='р̣̄' order='3' />
  <entry from='&#x0068;' to='р̣' />
  <entry from='&#x0069;' to='ш́' />
  <entry from='&#x006A;' to='о̃' />
  <entry from='&#x006B;' to='л̣' />
  <entry from='&#x006C;' to='д̣' />
  <entry from='&#x006E;' to='т̣' />
  <entry from='&#x006F;' to='ш̣' />
  <entry from='&#x0071;' to='и̃' />
  <entry from='&#x0072;' to='р̇' />
  <entry from='&#x0074;' to='н̣' />
  <entry from='&#x0075;' to='н̃' />
  <entry from='&#x0076;' to='м̇' />
  <entry from='&#x0079;' to='н̇' />
  <entry from='&#x007A;' to='у̃' />
  <entry from='&#x007B;' to='х̣' />
</mapping>

=== gvp/gvp-word-addin/WordAddIn/Maps/UnicodeToCP1252.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  This mapping is meant for converting Unicode codepoints
  that refer to range 0x80-0x9F of the CP1252 codepage back into CP1252.
  This is necessary for TTF/OTF fonts that were generated out of
  Type 1 font. These codes will be further converted in other mappings.

  See:
    - https://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP1252.TXT
    - https://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WindowsBestFit/bestfit1252.txt
-->
<mapping xsi:noNamespaceSchemaLocation="Mapping.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <entry from="&#x20AC;" to="&#x80;"/>
  <!-- <entry from="&#x;" to="&#x81;" /> -->
  <entry from="&#x201A;" to="&#x82;"/>
  <entry from="&#x0192;" to="&#x83;"/>
  <entry from="&#x201E;" to="&#x84;"/>
  <entry from="&#x2026;" to="&#x85;"/>
  <entry from="&#x2020;" to="&#x86;"/>
  <entry from="&#x2021;" to="&#x87;"/>
  <entry from="&#x02C6;" to="&#x88;"/>
  <entry from="&#x2030;" to="&#x89;"/>
  <entry from="&#x0160;" to="&#x8A;"/>
  <entry from="&#x2039;" to="&#x8B;"/>
  <entry from="&#x0152;" to="&#x8C;"/>
  <!-- <entry from="&#x;" to="&#x8D;" /> -->
  <entry from="&#x017D;" to="&#x8E;"/>
  <!-- <entry from="&#x;" to="&#x8F;" /> -->
  <!-- <entry from="&#x;" to="&#x90;" /> -->
  <entry from="&#x2018;" to="&#x91;"/>
  <entry from="&#x2019;" to="&#x92;"/>
  <entry from="&#x201C;" to="&#x93;"/>
  <entry from="&#x201D;" to="&#x94;"/>
  <entry from="&#x2022;" to="&#x95;"/>
  <entry from="&#x2013;" to="&#x96;"/>
  <entry from="&#x2014;" to="&#x97;"/>
  <entry from="&#x02DC;" to="&#x98;"/>
  <entry from="&#x2122;" to="&#x99;"/>
  <entry from="&#x0161;" to="&#x9A;"/>
  <entry from="&#x203A;" to="&#x9B;"/>
  <entry from="&#x0153;" to="&#x9C;"/>
  <!-- <entry from="&#x;" to="&#x9D;" /> -->
  <entry from="&#x017E;" to="&#x9E;"/>
  <entry from="&#x0178;" to="&#x9F;"/>
</mapping>

=== gvp/gvp-word-addin/WordAddIn/Maps/Devanagari/UnicodeToAARituPlus2.xml
<?xml version="1.0" encoding="utf-8" ?>
<mapping xsi:noNamespaceSchemaLocation="..\Mapping.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xi="http://www.w3.org/2001/XInclude">

<!-- Small I and Half R-->
  <entry from='र्([\u0915-\u0939](\u094D[\u0915-\u0939])*[\u093A\u093B\u093E-\u094C]?)\u093F\u0902' to='&#xB2;$1' type="regex" comment="r+consonant+im" />
  <entry from='र्([\u0915-\u0939](\u094D[\u0915-\u0939])*[\u093A\u093B\u093E-\u094C]?)\u093F' to='&#xA3;$1' type="regex" comment="r+consonant+i" />
  <entry from='र्([\u0915-\u0939]\u094D)*\u0915\u0902' to='$1&#2325;&#x97;' type="regex" comment="r+k+m" /> 
  <entry from='र्([\u0915-\u0939]\u094D)*\u0915' to='$1&#2325;&#x96;' type="regex" comment="r+k" /> 
  <entry from='र्([\u0915-\u0939](\u094D[\u0915-\u0939])*[\u093A\u093B\u093E-\u094C]?)\u0092' to='$1&#xB1;' type="regex" comment="r+consonant+m" /> 
  <entry from='र्([\u0915-\u0939](\u094D[\u0915-\u0939])*[\u093A\u093B\u093E-\u094C]?)' to='$1&#x5A;' type="regex" comment="r+consonant" /> 
  <entry from='([\u0915-\u0939](\u094D[\u0915-\u0939])*)\u093F\u0902' to='&#xA5;$1' type="regex" comment="consonant+im"  />
  <entry from='([\u0915-\u0939](\u094D[\u0915-\u0939])*)\u093F' to='&#x66;$1' type="regex" comment="consonant+i" />
  
<!-- Punctuation-->
  <entry from='-' to='&#x26;' />
  <entry from='–' to='&#x26;' />
  <entry from='—' to='&#xB5;' />
  <entry from='+' to='&#x24;' />
  <entry from='”' to='&#x2A;&#x2A;' />
  <entry from='’' to='&#x2A;' />
  <entry from='/' to='&#x40;' />
  <entry from='“' to='&#x5E;&#x5E;' />
  <entry from='‘' to='&#x5E;' />
  <entry from=';' to='&#x5F;' />
  <entry from='&lt;' to='&#x9E;' />
  <entry from='&gt;' to='&#x9F;' />
  <entry from='÷' to='&#xBB;' />
  <entry from='=' to='&#xBE;' />
  <entry from='&#x0903;' to='&#x25;' comment="Visarga" />
  <entry from='ऺ' to='&#xFA;' />
  <entry from='।' to='&#x41;' />
  <entry from='॥' to='&#xFB;' />
  <entry from='[' to='&#xFD;' />
  <entry from=']' to='&#xFE;' />
  <entry from=':' to='&#x25;' />
  <entry from='.' to='&#x2D;' />
  <entry from='?' to='&#x5C;' />
  <entry from=',' to='&#x5D;' />

<!-- Conjuncts-->
  <entry from='क्ष्' to='&#x7B;' />
  <entry from='क्ष' to='&#x7B;&#x6B;' />
  <entry from='द्य' to='&#x7C;' />
  <entry from='द्व' to='&#x7D;' />
  <entry from='रु' to='&#x23;' />
  <entry from='रू' to='&#x3A;' />
  <entry from='त्र्' to='&#xAB;' />
  <entry from='ॐ' to='&#xAC;' />
  <entry from='त्र' to='&#x3D;' />
  <entry from='श्र' to='&#x4A;' />
  <entry from='ज्ञ' to='&#x4B;' />
  <entry from='क्र' to='&#xD8;' />
  <entry from='ख्र' to='&#xD2;' />
  <entry from='छ्र' to='&#x4E;&#xAA;' />
  <entry from='ट्र' to='&#x56;&#xAA;' />
  <entry from='ठ्र' to='&#x42;&#xAA;' />
  <entry from='ड्र' to='&#x4D;&#xAA;' />
  <entry from='ढ्र' to='&#x3C;&#xAA;' />
  <entry from='फ्र' to='&#xDD;' />
  <entry from='ल्र' to='&#x79;&#xAA;' />
  <entry from='ह्र' to='&#x56;&#xAA;' />
  <entry from='ॐ' to='&#xAC;' />
  <entry from='द्ध' to='&#xBC;' />
  <entry from='ङ्क्ष' to='&#xC0;' />
  <entry from='ङ्क्त' to='&#xC9;' />
  <entry from='ङ्क' to='&#xC1;' />
  <entry from='ङ्ग' to='&#xC2;' />
  <entry from='ङ्ख' to='&#xCC;' />
  <entry from='ङ्घ' to='&#xD0;' />
  <entry from='ह्न' to='&#xCA;' />
  <entry from='ह्ल' to='&#xCD;' />
  <entry from='ह्र' to='&#xCE;' />
  <entry from='कृ' to='&#xCF;' />
  <entry from='त्त्' to='&#xD9;' />
  <entry from='द्भ' to='&#xDA;' />
  <entry from='ह्व' to='&#xE0;' />
  <entry from='ह्य' to='&#xE1;' />
  <entry from='हृ' to='&#xE2;' />
  <entry from='ह्म' to='&#xE3;' />
  <entry from='क्त' to='&#xE4;' />
  <entry from='द्ग' to='&#xE5;' />
  <entry from='द्र' to='&#xE6;' />
  <entry from='न्न्' to='&#xE9;' />
  <entry from='ट्ट' to='&#xEA;' />
  <entry from='ट्ठ' to='&#xEB;' />
  <entry from='ड्ड' to='&#xEC;' />
  <entry from='द्द' to='&#xED;' />
  <entry from='ड्ढ' to='&#xEF;' />
  <entry from='स्र' to='&#xF2;' />
  <entry from='ह्ण' to='&#xF7;' />
  <entry from='द्म' to='&#xF9;' />
  <entry from='प्त' to='&#xF0;' />
  <entry from='प्र' to='&#xE7;' />
  
<!-- Vowels-->
  <entry from='अ' to='&#x76;' />
  <entry from='आ' to='&#x76;&#x6B;' />
  <entry from='इ' to='&#x62;' />
  <entry from='ई' to='&#x62;&#x5A;' />
  <entry from='उ' to='&#x6D;' />
  <entry from='ऊ' to='&#xC5;' />
  <entry from='ऋ' to='&#xBD;' />
  <entry from='ॠ' to='&#xBF;' />
  <entry from='ऌ' to='&#xC8;' />
  <entry from='ए' to='&#x2C;' />
  <entry from='ऐ' to='&#x2C;&#x73;' />
  <entry from='ओ' to='&#x76;&#x6B;&#x73;' />
  <entry from='औ' to='&#x76;&#x6B;&#x53;' />
  <entry from='ा' to='&#x6B;' />
  <entry from='ी' to='&#x68;' />
  <entry from='ु' to='&#x71;' />
  <entry from='ू' to='&#x77;' />
  <entry from='ृ' to='&#x60;' />
  <entry from='ॄ' to='&#xA4;' />
  <entry from='ॢ' to='&#xC6;' />
  <entry from='े' to='&#x73;' />
  <entry from='ै' to='&#x53;' />
  <entry from='ो' to='&#x6B;&#x73;' />
  <entry from='ौ' to='&#x6B;&#x53;' />
  <entry from='ँ' to='&#xA1;' />
  <entry from='ऽ' to='&#xB7;' />
  <entry from='&#x0902;' to='&#x61;' comment="Anusvara" />
  <entry from='ॅ' to='&#x57;' />
  
<!-- Consonants-->
  <entry from='ष्' to='&#x22;' />
  <entry from='ष' to='&#x22;&#x6B;' />
  <entry from='श्' to='&#x27;' />
  <entry from='श' to='&#x27;&#x6B;' />
  <entry from='&#x093C;' to='&#x2B;' comment="Nukta" />
  <entry from='ण्' to='&#x2E;' />
  <entry from='ण' to='&#x2E;&#x6B;' />
  <entry from='ध्' to='&#x2F;' />
  <entry from='ध' to='&#x2F;&#x6B;' />
  <entry from='ञ्' to='&#xB4;' />
  <entry from='फ्' to='&#xB6;' />
  <entry from='य्' to='&#xB8;' />
  <entry from='ह्' to='&#xBA;' />
  <entry from='झ्' to='&#xD6;' />
  <entry from='य' to='&#x3B;' />
  <entry from='ढ' to='&#x3C;' />
  <entry from='झ' to='&#x3E;' />
  <entry from='घ्' to='&#x3F;' />
  <entry from='घ' to='&#x3F;&#x6B;' />
  <entry from='ठ' to='&#x42;' />
  <entry from='ब्' to='&#x43;' />
  <entry from='क्' to='&#x44;' />
  <entry from='म्' to='&#x45;' />
  <entry from='थ्' to='&#x46;' />
  <entry from='थ' to='&#x46;&#x6B;' />
  <entry from='भ्' to='&#x48;' />
  <entry from='भ' to='&#x48;&#x6B;' />
  <entry from='प्' to='&#x49;' />
  <entry from='स्' to='&#x4C;' />
  <entry from='ड' to='&#x4D;' />
  <entry from='छ' to='&#x4E;' />
  <entry from='व्' to='&#x4F;' />
  <entry from='च्' to='&#x50;' />
  <entry from='फ' to='&#x51;' />
  <entry from='त्' to='&#x52;' />
  <entry from='ज्' to='&#x54;' />
  <entry from='न्' to='&#x55;' />
  <entry from='ट' to='&#x56;' />
  <entry from='ग्' to='&#x58;' />
  <entry from='ल्' to='&#x59;' />
  <entry from='ख्' to='&#x5B;' />
  <entry from='ख' to='&#x5B;&#x6B;' />
  <entry from='ब' to='&#x63;' />
  <entry from='क' to='&#x64;' />
  <entry from='म' to='&#x65;' />
  <entry from='ह' to='&#x67;' />
  <entry from='प' to='&#x69;' />
  <entry from='र' to='&#x6A;' />
  <entry from='स' to='&#x6C;' />
  <entry from='द' to='&#x6E;' />
  <entry from='व' to='&#x6F;' />
  <entry from='च' to='&#x70;' />
  <entry from='त' to='&#x72;' />
  <entry from='ज' to='&#x74;' />
  <entry from='न' to='&#x75;' />
  <entry from='अ' to='&#x76;' />
  <entry from='ग' to='&#x78;' />
  <entry from='ल' to='&#x79;' />
  <entry from='्र' to='&#x7A;' />
  <entry from='ङ' to='&#xB3;' />
  <entry from='ळ' to='&#xFF;' />
  
<!-- Numbers-->
  <entry from='१' to='&#x83;' />
  <entry from='२' to='&#x84;' />
  <entry from='३' to='&#x85;' />
  <entry from='४' to='&#x86;' />
  <entry from='५' to='&#x87;' />
  <entry from='६' to='&#x88;' />
  <entry from='७' to='&#x89;' />
  <entry from='८' to='&#x8A;' />
  <entry from='९' to='&#x8B;' />
  <entry from='०' to='&#x8C;' />
  <entry from='1' to='&#x83;' />
  <entry from='2' to='&#x84;' />
  <entry from='3' to='&#x85;' />
  <entry from='4' to='&#x86;' />
  <entry from='5' to='&#x87;' />
  <entry from='6' to='&#x88;' />
  <entry from='7' to='&#x89;' />
  <entry from='8' to='&#x8A;' />
  <entry from='9' to='&#x8B;' />
  <entry from='0' to='&#x8C;' />
  
</mapping>

=== gvp/gvp-word-addin/WordAddIn/Maps/Devanagari/AA.Common.Pre.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xsi:noNamespaceSchemaLocation="..\Mapping.xsd"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:xi="http://www.w3.org/2001/XInclude">
  <mapping name="Mistypings">
    <entry from="fq" to="qf" order="-110" comment="Wrong order of ु and ि" />
    <entry from="~+" to="+~" order="-110" comment="Wrong order of Virama and Nukta" />
    <entry from="·a" to="a·" order="-110" comment="Wrong order of Anusvar and Avagraha" />
    <entry from="*~" to="~*" order="-110" comment="Wrong order of Virama and Apostrophe" />
    <entry from="([Z±])+([`sq])+" to="$2$1" type="regex" order="-110" comment="R-before should be before E-matra, Ri, U-sign'/&gt;" />
    <entry from="~(?=[î])" to="" type="regex" order="-110" comment="Mistaken Virama in the middle of the conjunct" />
    <entry from="([Zqs])k" to="k$1" type="regex" order="-110" comment="Wrong order of A-sign and [R-before, U-sign]" />
    <entry from="(?&lt;=h)k+" to="" type="regex" order="-101" comment="a-sign is not allowed after i-sign" />
    <entry from="(?&lt;=[prtliecK=&amp;lt;;ux|])(k){2,}" to="$1" type="regex" order="-101" comment="Extra A-sign after consonants with vertical line" />
    <entry from="([ZzSs~])\1+" to="$1" type="regex" order="-101" comment="Duplicate symbol" />
    <entry from="±Z|Z±" to="±" type="regex" order="-100" comment="r+cons+m eats r+cons" />
    <entry from="sS|Ss" to="S" type="regex" order="-100" comment="AI-matra eats E-matra" />
  </mapping>
  <mapping name="Precombined Vowels">
    <entry from="bZ" to="ई" order="-10" />
    <entry from="b±" to="ईं" order="-10" />
    <entry from="mG" to="ऊ" order="-10" comment="Appendix for the long U." />
  </mapping>
</mapping>

=== gvp/gvp-word-addin/WordAddIn/Maps/Devanagari/AA.Common.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xsi:noNamespaceSchemaLocation="..\Mapping.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <entry from="&#x22;" to="ष्" />
  <entry from="&#x23;" to="रु" />
  <entry from="&#x24;" to="+" order="1" />
  <entry from="&#x25;" to="&#x0903;" comment="Visarga" />
  <entry from="&#x26;" to="–" order="1" />
  <entry from="&#x27;" to="श्" />
  <entry from="&#x2A;" to="’" order="1" />
  <entry from="&#x2B;" to="&#x093C;" comment="Nukta" />
  <entry from="&#x2C;" to="ए" />
  <entry from="&#x2D;" to="." order="1" />
  <entry from="&#x2E;" to="ण्" />
  <entry from="&#x2F;" to="ध्" />
  <entry from="&#x3A;" to="रू" />
  <entry from="&#x3B;" to="य" />
  <entry from="&#x3C;" to="ढ" />
  <entry from="&#x3D;" to="त्र" />
  <entry from="&#x3E;" to="झ" />
  <entry from="&#x3F;" to="घ्" />
  <entry from="&#x40;" to="/" order="1" />
  <entry from="&#x41;" to="।" />
  <entry from="&#x42;" to="ठ" />
  <entry from="&#x43;" to="ब्" />
  <entry from="&#x44;" to="क्" />
  <entry from="&#x45;" to="म्" />
  <entry from="&#x46;" to="थ्" />
  <!-- Codepoint x47 is mapped in Pre -->
  <entry from="&#x48;" to="भ्" />
  <entry from="&#x49;" to="प्" />
  <entry from="&#x4A;" to="श्र" />
  <entry from="&#x4B;" to="ज्ञ" />
  <entry from="&#x4C;" to="स्" />
  <entry from="&#x4D;" to="ड" />
  <entry from="&#x4E;" to="छ" />
  <entry from="&#x4F;" to="व्" />
  <entry from="&#x50;" to="च्" />
  <entry from="&#x51;" to="फ" />
  <entry from="&#x52;" to="त्" />
  <entry from="&#x53;" to="ै" />
  <entry from="&#x54;" to="ज्" />
  <entry from="&#x55;" to="न्" />
  <entry from="&#x56;" to="ट" />
  <entry from="&#x57;" to="ॅ" />
  <entry from="&#x58;" to="ग्" />
  <entry from="&#x59;" to="ल्" />
  <!-- Codepoint x5A is mapped in Post-->
  <entry from="&#x5B;" to="ख्" />
  <entry from="&#x5C;" to="?" order="1" />
  <entry from="&#x5D;" to="," order="1" />
  <entry from="&#x5E;" to="‘" order="1" />
  <entry from="&#x5F;" to=";" order="1" />
  <entry from="&#x60;" to="ृ" />
  <entry from="&#x61;" to="&#x0902;" comment="Anusvara" />
  <entry from="&#x62;" to="इ" />
  <entry from="&#x63;" to="ब" />
  <entry from="&#x64;" to="क" />
  <entry from="&#x65;" to="म" />
  <!-- Codepoint x66 is mapped in Post-->
  <entry from="&#x67;" to="ह" />
  <entry from="&#x68;" to="ी" />
  <entry from="&#x69;" to="प" />
  <entry from="&#x6A;" to="र" />
  <entry from="&#x6B;" to="ा" />
  <entry from="&#x6C;" to="स" />
  <entry from="&#x6D;" to="उ" />
  <entry from="&#x6E;" to="द" />
  <entry from="&#x6F;" to="व" />
  <entry from="&#x70;" to="च" />
  <entry from="&#x71;" to="ु" />
  <entry from="&#x72;" to="त" />
  <entry from="&#x73;" to="े" />
  <entry from="&#x74;" to="ज" />
  <entry from="&#x75;" to="न" />
  <entry from="&#x76;" to="अ" />
  <entry from="&#x77;" to="ू" />
  <entry from="&#x78;" to="ग" />
  <entry from="&#x79;" to="ल" />
  <entry from="&#x7A;" to="्र" />
  <entry from="&#x7B;" to="क्ष्" />
  <entry from="&#x7C;" to="द्य" />
  <entry from="&#x7D;" to="द्व" />
  <entry from="&#x7E;" to="&#x094D;&#x200C;" comment="Explicit halant" />
  <!-- Codepoint x7F–x82 is fonts-specific -->
  <!-- Codepoint x83–x8C is mapped in Numbers -->
  <!-- Codepoint x8D–x8F is fonts-specific -->
  <!-- Codepoint x90 is not defined -->
  <!-- Codepoint x91–x9C is fonts-specific -->
  <!-- Codepoint x9D is not defined -->
  <entry from="&#x9E;" to="&lt;" order="1" comment="Except for AAVishal"/>
  <entry from="&#x9F;" to="&gt;" order="1" />
  <!-- Codepoint xA0 is not defined -->
  <entry from="&#xA1;" to="&#x0901;" comment="Chandrabindu" />
  <!-- Codepoint xA2 is not defined -->
  <!-- Codepoint xA3 is mapped in Post -->
  <!-- Codepoint xA4 is fonts-specific -->
  <!-- Codepoint xA5 is mapped in Post -->
  <!-- Codepoint xA6 is not defined -->
  <entry from="&#xA7;" to="ठ्ठ" />
  <entry from="&#xA8;" to="ु" />
  <entry from="&#xA9;" to="ू" />
  <entry from="&#xAA;" to="्र" />
  <entry from="&#xAB;" to="त्र्" />
  <entry from="&#xAC;" to="ॐ" />
  <!-- Codepoint xAD is not defined -->
  <entry from="&#xAE;" to="ैं" />
  <!-- Codepoint xAF is not defined -->
  <entry from="&#xB0;" to="ीं" />
  <!-- Codepoint xB1 is mapped in Post -->
  <!-- Codepoint xB2 is mapped in Post -->
  <entry from="&#xB3;" to="ङ" />
  <entry from="&#xB4;" to="ञ्" />
  <entry from="&#xB5;" to="—" order="1" />
  <entry from="&#xB6;" to="फ्" />
  <entry from="&#xB7;" to="ऽ" />
  <entry from="&#xB8;" to="य्" />
  <!-- Codepoint xB9 is fonts-specific -->
  <entry from="&#xBA;" to="ह्" />
  <entry from="&#xBB;" to="÷" order="1" />
  <entry from="&#xBC;" to="द्ध" />
  <entry from="&#xBD;" to="ऋ" />
  <entry from="&#xBE;" to="=" order="1" />
  <entry from="&#xBF;" to="ॠ" />
  <!-- Codepoint xC0 is fonts-specific -->
  <entry from="&#xC1;" to="ङ्क" />
  <entry from="&#xC2;" to="ङ्ग" />
  <!-- Codepoint xC3 is not defined -->
  <!-- Codepoint xC4 is fonts-specific -->
  <entry from="&#xC5;" to="ऊ" />
  <!-- Codepoint xC6 is fonts-specific -->
  <!-- Codepoint xC7 is not defined -->
  <!-- Codepoint xC8 is fonts-specific -->
  <!-- Codepoint xC9 is fonts-specific -->
  <entry from="&#xCA;" to="ह्न" />
  <!-- Codepoint xCB is fonts-specific -->
  <!-- Codepoint xCC is fonts-specific -->
  <entry from="&#xCD;" to="ह्ल" />
  <entry from="&#xCE;" to="ह्र" />
  <entry from="&#xCF;" to="कृ" />
  <!-- Codepoint xD0 is fonts-specific -->
  <!-- Codepoint xD1 is not defined -->
  <entry from="&#xD2;" to="ख्र" />
  <entry from="&#xD3;" to="श्" />
  <!-- Codepoint xD4 is fonts-specific -->
  <!-- Codepoint xD5 is fonts-specific -->
  <entry from="&#xD6;" to="झ्" />
  <!-- Codepoint xD7 is fonts-specific -->
  <entry from="&#xD8;" to="क्र" />
  <entry from="&#xD9;" to="त्त्" />
  <entry from="&#xDA;" to="द्भ" />
  <entry from="&#xDB;" to="&#x093C;" comment="Nukta" />
  <entry from="&#xDC;" to="श्" />
  <entry from="&#xDD;" to="फ्र" />
  <entry from="&#xDE;" to="”" order="1" />
  <entry from="&#xDF;" to="“" order="1" />
  <entry from="&#xE0;" to="ह्व" />
  <entry from="&#xE1;" to="ह्य" />
  <entry from="&#xE2;" to="हृ" />
  <entry from="&#xE3;" to="ह्म" />
  <entry from="&#xE4;" to="क्त" />
  <entry from="&#xE5;" to="द्ग" />
  <entry from="&#xE6;" to="द्र" />
  <entry from="&#xE7;" to="प्र" />
  <entry from="&#xE8;" to="ध्" />
  <entry from="&#xE9;" to="न्न्" />
  <entry from="&#xEA;" to="ट्ट" />
  <entry from="&#xEB;" to="ट्ठ" />
  <entry from="&#xEC;" to="ड्ड" />
  <entry from="&#xED;" to="द्द" />
  <entry from="&#xEE;" to="्य" />
  <entry from="&#xEF;" to="ड्ढ" />
  <!-- Codepoint xF0 is fonts-specific -->
  <entry from="&#xF1;" to="॰" />
  <entry from="&#xF2;" to="स्र" />
  <entry from="&#xF3;" to="स्त्र" />
  <entry from="&#xF4;" to="क्क" />
  <!-- Codepoint xF5 is fonts-specific -->
  <entry from="&#xF6;" to="&#x0947;&#x0901;" comment="Vowel sign E with chandra bindu" />
  <entry from="&#xF7;" to="ह्ण" />
  <!-- Codepoint xF8 is fonts-specific -->
  <entry from="&#xF9;" to="द्म" />
  <entry from="&#xFA;" to="ऺ" />
  <entry from="&#xFB;" to="॥" />
  <entry from="&#xFC;" to="ें" />
  <entry from="&#xFD;" to="[" order="1" />
  <entry from="&#xFE;" to="]" order="2" comment="This mapping should have order greated than mapping of ]" />
  <!-- Codepoint xFF is fonts-specific -->
</mapping>

=== gvp/gvp-word-addin/WordAddIn/Maps/Devanagari/AA.Common.Normal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
//"Sign",
//"Conjuncts",
//"Conjunct + Virama",
//"Conjunct + Vowel sign",
//"Consonants",
//"Consonant + Virama",
//"Consonant + Vowel",
//"Consonant + Vowel sign",
//"Virama + Consonant",
//"Vowels",
//"Vowel sign",
-->
<mapping xsi:noNamespaceSchemaLocation="..\Mapping.xsd"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <mapping name="Numbers">
    <entry from="Œ" to="०" order="20" comment="0" />
    <entry from="ƒ" to="१" order="20" comment="1" />
    <entry from="„" to="२" order="20" comment="2" />
    <entry from="…" to="३" order="20" comment="3" />
    <entry from="†" to="४" order="20" comment="4" />
    <entry from="‡" to="५" order="20" comment="5" />
    <entry from="ˆ" to="६" order="20" comment="6" />
    <entry from="‰" to="७" order="20" comment="7" />
    <entry from="Š" to="८" order="20" comment="8" />
    <entry from="‹" to="९" order="20" comment="9" />
  </mapping>

  <entry from="¬" to="ॐ" />
  <entry from="v" to="अ" comment="а" />
  <entry from="b" to="इ" comment="и" />
  <entry from="m" to="उ" comment="у" />
  <entry from="Å" to="ऊ" comment="ӯ" />
  <entry from="½" to="ऋ" comment="р̣" />
  <entry from="¿" to="ॠ" comment="р̣̄" />
  <entry from="," to="ए" comment="э" />
  <entry from="d" to="क" comment="ка" />
  <entry from="Ï" to="कृ" comment="кр̣" />
  <entry from="D" to="क्" comment="к" />
  <entry from="ô" to="क्क" comment="кка" />
  <entry from="ä" to="क्त" comment="кта" />
  <entry from="Ø" to="क्र" comment="кра" />
  <entry from="{" to="क्ष्" comment="кш̣" />
  <entry from="[" to="ख्" comment="кх" />
  <entry from="Ò" to="ख्र" comment="кхра" />
  <entry from="x" to="ग" comment="га" />
  <entry from="X" to="ग्" comment="г" />
  <entry from="?" to="घ्" comment="гх" />
  <entry from="³" to="ङ" comment="н̇а" />
  <entry from="Á" to="ङ्क" comment="н̇ка" />
  <entry from="Â" to="ङ्ग" comment="н̇га" />
  <entry from="p" to="च" comment="ча" />
  <entry from="P" to="च्" comment="ч" />
  <entry from="N" to="छ" comment="чха" />
  <entry from="t" to="ज" comment="джа" />
  <entry from="T" to="ज्" comment="дж" />
  <entry from="K" to="ज्ञ" comment="джн̃а" />
  <entry from="&gt;" to="झ" comment="джха" />
  <entry from="Ö" to="झ्" comment="джх" />
  <entry from="´" to="ञ्" comment="н̃" />
  <entry from="V" to="ट" comment="т̣а" />
  <entry from="ê" to="ट्ट" comment="т̣т̣а" />
  <entry from="ë" to="ट्ठ" comment="т̣т̣ха" />
  <entry from="B" to="ठ" comment="тх̣а" />
  <entry from="§" to="ठ्ठ" comment="т̣хт̣ха" />
  <entry from="M" to="ड" comment="д̣а" />
  <entry from="ì" to="ड्ड" comment="д̣д̣а" />
  <entry from="ï" to="ड्ढ" comment="д̣д̣ха" />
  <entry from="&lt;" to="ढ" comment="дх̣а" />
  <entry from="." to="ण्" comment="н̣" />
  <entry from="r" to="त" comment="та" />
  <entry from="R" to="त्" comment="т" />
  <entry from="Ù" to="त्त्" comment="тт" />
  <entry from="=" to="त्र" comment="тра" />
  <entry from="«" to="त्र्" comment="тр" />
  <entry from="F" to="थ्" comment="тх" />
  <entry from="n" to="द" comment="да" />
  <entry from="å" to="द्ग" comment="дга" />
  <entry from="í" to="द्द" comment="дда" />
  <entry from="¼" to="द्ध" comment="ддха" />
  <entry from="Ú" to="द्भ" comment="дбха" />
  <entry from="ù" to="द्म" comment="дма" />
  <entry from="|" to="द्य" comment="дйа" />
  <entry from="æ" to="द्र" comment="дра" />
  <entry from="}" to="द्व" comment="два" />
  <entry from="/" to="ध्" comment="дх" />
  <entry from="è" to="ध्" comment="дх" />
  <entry from="u" to="न" comment="на" />
  <entry from="U" to="न्" comment="н" />
  <entry from="é" to="न्न्" comment="нн" />
  <entry from="i" to="प" comment="па" />
  <entry from="I" to="प्" comment="п" />
  <entry from="ç" to="प्र" comment="пра" />
  <entry from="Q" to="फ" comment="пха" />
  <entry from="¶" to="फ्" comment="пх" />
  <entry from="Ý" to="फ्र" comment="пхра" />
  <entry from="c" to="ब" comment="ба" />
  <entry from="C" to="ब्" comment="б" />
  <entry from="H" to="भ्" comment="бх" />
  <entry from="e" to="म" comment="ма" />
  <entry from="E" to="म्" comment="м" />
  <entry from=";" to="य" comment="йа" />
  <entry from="¸" to="य्" comment="й" />
  <entry from="j" to="र" comment="ра" />
  <entry from="#" to="रु" comment="ру" />
  <entry from=":" to="रू" comment="рӯ" />
  <entry from="y" to="ल" comment="ла" />
  <entry from="Y" to="ल्" comment="л" />
  <entry from="o" to="व" comment="ва" />
  <entry from="O" to="व्" comment="в" />
  <entry from="'" to="श्" comment="ш́" />
  <entry from="Ó" to="श्" comment="ш́ (как в श्क) first letter" />
  <entry from="Ü" to="श्" comment="ш́ (как в श्र, श्व)" />
  <entry from="J" to="श्र" comment="ш́ра" />
  <entry from="&quot;" to="ष्" comment="ш̣" />
  <entry from="l" to="स" comment="са" />
  <entry from="L" to="स्" comment="с" />
  <entry from="ó" to="स्त्र" comment="стра" />
  <entry from="ò" to="स्र" comment="сра" />
  <entry from="g" to="ह" comment="ха" />
  <entry from="â" to="हृ" comment="хр̣" />
  <entry from="º" to="ह्" comment="х" />
  <entry from="÷" to="ह्ण" comment="хн̣а" />
  <entry from="Ê" to="ह्न" comment="хна" />
  <entry from="ã" to="ह्म" comment="хма" />
  <entry from="á" to="ह्य" comment="хйа" />
  <entry from="Î" to="ह्र" comment="хра" />
  <entry from="Í" to="ह्ल" comment="хла" />
  <entry from="à" to="ह्व" comment="хва" />
  <entry from="·" to="ऽ" comment="апостроф" />
  <entry from="k" to="ा" comment="а̄" />
  <entry from="h" to="ी" comment="ӣ" />
  <entry from="°" to="ीं" comment="ӣм̣" />
  <entry from="q" to="ु" comment="у" />
  <entry from="¨" to="ु" comment="у (пониже)" />
  <entry from="w" to="ू" comment="ӯ" />
  <entry from="©" to="ू" comment="ӯ (пониже)" />
  <entry from="`" to="ृ" comment="р̣" />
  <entry from="W" to="ॅ" comment="чандра е" />
  <entry from="s" to="े" comment="е или" />
  <entry from="˜" to="ें" />
  <entry from="ü" to="ें" comment="ем̇" />
  <entry from="S" to="ै" comment="аи" />
  <entry from="®" to="ैं" comment="аим̣" />
  <entry from="~" to="&#x094D;&#x200C;" comment="Explicit halant" />
  <entry from="î" to="्य" comment="й (как в ड्य)" />
  <entry from="z" to="्र" comment="ра (как в प्र)" />
  <entry from="ª" to="्र" comment="ра (как в ड्र)" />
  <entry from="ú" to="ऺ" comment="udatta or U+093A   DEVANAGARI VOWEL SIGN OE" />
</mapping>
